### ISSUE TITLE
Install issue: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-l3Cedr-build/

### ISSUE THREAD

**Issue by R0yk3** [markruys/gw2pvo#12]
Using raspberry

Solved the issue by doing the following:
sudo pip install —upgrade setuptools

Changing the install command:
pip install https://github.com/markruys/gw2pvo/releases/download/1.2.1/gw2pvo-1.2.1.tar.gz
by
pip3 install https://github.com/markruys/gw2pvo/releases/download/1.2.1/gw2pvo-1.2.1.tar.gz

Installed no errors.

**Comment by markruys** [comment]
I think the new installation command will work beter as it also installs dependencies:
```
sudo pip3 install https://github.com/markruys/gw2pvo/releases/download/1.3.2/gw2pvo-1.3.2-py3-none-any.whl
```
