### ISSUE TITLE
the fixes for the temperature are not in the release

### ISSUE THREAD

**Issue by daemenseth** [markruys/gw2pvo#15]
Can you make a new release with the latest fixes?
SO I can that use in the docker image

**Comment by daemenseth** [comment]
I have fixed it I download the zip from the master and overwrite the files

**Comment by kingfisher02** [comment]
Don't forget to change the installation instructions, it still points to version 1.2.1 :)

**Comment by markruys** [comment]
I guess you mean the code change from #17. So I close this issue as a duplicate.
