### ISSUE TITLE
the first value for the day is too high

### ISSUE THREAD

**Issue by daemenseth** [markruys/gw2pvo#16]
I using this project since yesterday but todays first import is too high
it is 1800

In the logging I see also the v1 is 1800
What can cause this issue.
I have implemted the fixes from @vijghph 
https://pvoutput.org/intraday.jsp?id=74365&sid=65959&dt=20190326

**Comment by X-gen76** [comment]
I got the same problem since 7 days ago.

**Comment by Ralf7** [comment]
Since April 19 I've got this issue too. See https://pvoutput.org/intraday.jsp?id=62026&sid=55213
I think something has changed on the GoodWe server, because I haven't changed anything. 
I hope somebody has got a solution for this, as my solar array is facing west, I can see the real values only from 1PM on.

**Comment by walterwhite81** [comment]
Same here, starts with 4.550kWh every day.

**Comment by vkevin85** [comment]
Same problem here, however de starting value of the day is different from day to day. Already applied the fix from [vijghph](https://github.com/markruys/gw2pvo/pull/11) but it doesn't seem to make any difference. Hopefuly someone can help to fix this issue.

**Comment by tclaer** [comment]
same issue....

**Comment by X-gen76** [comment]
For the people how wants/needs an alternative:

https://github.com/zonoskar/Goodwe2PVoutput/

**Comment by Simanias** [comment]
To bad I'm having the same issue.
Besides this isseu, the script works great.

**Comment by JaapBraam** [comment]
Today this happened to me too... Yesterday I added the --skip-offline option. Maybe related?

**Comment by JaapBraam** [comment]
I investigated: 
I adapted the code to not use an average for the generated power, and now production starts at 0 kwh the next day.... I'll make a pull request for this...

**Comment by vkevin85** [comment]
Pulled the changes you made Jaap and it seems to work fine, thanks for your effort.

**Comment by X-Wizard** [comment]
Hi Jaap, I modified the script and it works, thanks!

2 Question,
- How to deal with two MPPT, is there a possibility to sum both MPPT?
- How to use the temperature value from the inverter?

**Comment by markruys** [comment]
Looks like people are happy about  #PR18, so I accepted it. Thank Jaap for you effort!

**Comment by walterwhite81** [comment]
This fixed it, thanks @JaapBraam !

**Comment by Ralf7** [comment]
How can I apply this fix? 
I’ve tried to reinstall the package, but I received notifications of duplicate files. Then reinstalled the package with —upgrade at the end. That resulted in some errors. 
Can anybody describe in easy-to-follow steps what to do?

**Comment by eNeRGy164** [comment]
As it's not a new release yet, you would need to build the package from source code yourself

**Comment by Ralf7** [comment]
Ok that’s a pity, in that case I will wait until a new version comes out.

**Comment by eNeRGy164** [comment]
Same here :)

**Comment by markruys** [comment]
I'll build a new release this evening (if don't forget it ;)

**Comment by markruys** [comment]
Build new release: https://github.com/markruys/gw2pvo/releases/tag/1.2.2

**Comment by Ralf7** [comment]
I installed the new release 3 days ago and it’s working like a charm! Thanks for the effort @JaapBraam and @markruys
