### ISSUE TITLE
Inverter with dual string

### ISSUE THREAD

**Issue by X-Wizard** [markruys/gw2pvo#19]
Gents,

I have an inverter with a dual string vpv1 and vpv2 (voltage), is there a possibility to sum both strings?

**Comment by X-Wizard** [comment]
Would be nice if we can sum both or more strings or has someone else a solution to tackle this?

**Comment by markruys** [comment]
I've created a [feature branch](https://github.com/markruys/gw2pvo/tree/feature/multiple_inverters) which should do the trick. I have only a single inverter, so can someone test this change?

**Comment by X-Wizard** [comment]
Hi Markruys,

I changed both files as requested, the output is 1 PV string shown on pvoutput.org.

**Comment by markruys** [comment]
Strange, can you show me the output of your `gw2pvo` invocation with the `--log debug` added?

**Comment by X-Wizard** [comment]
Hi Markruys,

Please find included in this email the requested data,

-- 

Jun 30 10:28:13 vps gw2pvo[18459]: DEBUG    Starting new HTTPS connection (1): semsportal.com:443
Jun 30 10:28:13 vps gw2pvo[18459]: DEBUG    https://semsportal.com:443 "POST /api/v2/PowerStation/GetMonitorDetailByPowerstationId HTTP/1.1" 200 300
Jun 30 10:28:13 vps gw2pvo[18459]: DEBUG    {'hasError': False, 'code': 100001, 'msg': 'No access, please login.', 'data': None, 'components': {'para': None, 'langVer': 73, 'timeSpan': 0, 'api': 'http://semsportal.com:82/api/v2/PowerStation/GetMonitorDetailByPowerstationId', 'msgSocketAdr': ''}}
Jun 30 10:28:13 vps gw2pvo[18459]: DEBUG    Starting new HTTPS connection (1): semsportal.com:443
Jun 30 10:28:13 vps gw2pvo[18459]: DEBUG    https://semsportal.com:443 "POST /api/v2/Common/CrossLogin HTTP/1.1" 200 527
Jun 30 10:28:14 vps gw2pvo[18459]: DEBUG    Starting new HTTPS connection (1): eu.semsportal.com:443
Jun 30 10:28:15 vps gw2pvo[18459]: DEBUG    https://eu.semsportal.com:443 "POST /api/v2/PowerStation/GetMonitorDetailByPowerstationId HTTP/1.1" 200 25114
Jun 30 10:28:15 vps gw2pvo[18459]: DEBUG    {'language': 'en', 'function': ['ADD', 'VIEW', 'EDIT', 'DELETE', 'INVERTER_A', 'INVERTER_E', 'INVERTER_D'], 'hasError': False, 'msg': 'success', 'code': '0', 'data': {'info': {'powerstation_id': '6bc75339-f48c-440f-a096-a1dc6bf74574', 'time': '06/30/2020 10:28:15', 'date_format': 'MM.dd.yyyy', 'date_format_ym': 'MM.yyyy', 'stationname': 'JP Energy House', 'address': 'A, Nederland ', 'owner_name': None, 'owner_phone': None, 'owner_email': '', 'battery_capacity': 0.0, 'turnon_time': '05/16/2019 00:00:00', 'create_time': '05/16/2019 01:12:55', 'capacity': 3.0, 'longitude':, 'latitude':, 'powerstation_type': 'residential', 'status': 1, 'is_stored': False, 'is_powerflow': False, 'charts_type': 4, 'has_pv': True, 'has_statistics_charts': False, 'only_bps': False, 'only_bpu': False, 'time_span': -2.0, 'pr_value': ''}, 'kpi': {'pac': 238.0, 'power': 0.3, 'total_power': 4081.4, 'day_income': 0.07, 'total_income': 914.23, 'yield_rate': 0.224, 'currency': 'EUR'}, 'images': ['https://oversea-gops.oss-cn-hongkong.aliyuncs.com/powerstation_img/1c5b6e89-c109-41b6-a5f0.jpeg', 'https://oversea-gops.oss-cn-hongkong.aliyuncs.com/powerstation_img/a8b8bf6d-0a31-4143-9a66.jpeg'], 'weather': {'HeWeather6': [{'daily_forecast': [{'cond_code_d': '300', 'cond_code_n': '300', 'cond_txt_d': 'Shower Rain', 'cond_txt_n': 'Shower Rain', 'date': '2020-06-30', 'time': '2020-06-30 00:00:00', 'hum': '90', 'pcpn': '4.8', 'pop': '67', 'pres': '1007', 'tmp_max': '19', 'tmp_min': '16', 'uv_index': '7', 'vis': '24', 'wind_deg': '245', 'wind_dir': 'SW', 'wind_sc': '3-4', 'wind_spd': '24'}, {'cond_code_d': '302', 'cond_code_n': '101', 'cond_txt_d': 'Thundershower', 'cond_txt_n': 'Cloudy', 'date': '2020-07-01', 'time': '2020-07-01 00:00:00', 'hum': '80', 'pcpn': '4.8', 'pop': '60', 'pres': '1006', 'tmp_max': '21', 'tmp_min': '15', 'uv_index': '4', 'vis': '24', 'wind_deg': '235', 'wind_dir': 'SW', 'wind_sc': '3-4', 'wind_spd': '16'}, {'cond_code_d': '300', 'cond_code_n': '100', 'cond_txt_d': 'Shower Rain', 'cond_txt_n': 'Clear', 'date': '2020-07-02', 'time': '2020-07-02 00:00:00', 'hum': '80', 'pcpn': '4.8', 'pop': '67', 'pres': '1012', 'tmp_max': '19', 'tmp_min': '12', 'uv_index': '6', 'vis': '24', 'wind_deg': '315', 'wind_dir': 'NW', 'wind_sc': '1-2', 'wind_spd': '10'}, {'cond_code_d': '101', 'cond_code_n': '101', 'cond_txt_d': 'Cloudy', 'cond_txt_n': 'Cloudy', 'date': '2020-07-03', 'time': '2020-07-03 00:00:00', 'hum': '77', 'pcpn': '0.0', 'pop': '25', 'pres': '1017', 'tmp_max': '20', 'tmp_min': '15', 'uv_index': '6', 'vis': '24', 'wind_deg': '229', 'wind_dir': 'SW', 'wind_sc': '3-4', 'wind_spd': '20'}, {'cond_code_d': '300', 'cond_code_n': '300', 'cond_txt_d': 'Shower Rain', 'cond_txt_n': 'Shower Rain', 'date': '2020-07-04', 'time': '2020-07-04 00:00:00', 'hum': '81', 'pcpn': '2.0', 'pop': '60', 'pres': '1015', 'tmp_max': '20', 'tmp_min': '13', 'uv_index': '2', 'vis': '19', 'wind_deg': '212', 'wind_dir': 'SW', 'wind_sc': '4-5', 'wind_spd': '26'}, {'cond_code_d': '300', 'cond_code_n': '103', 'cond_txt_d': 'Shower Rain', 'cond_txt_n': 'Partly Cloudy', 'date': '2020-07-05', 'time': '2020-07-05 00:00:00', 'hum': '78', 'pcpn': '0.6', 'pop': '55', 'pres': '1013', 'tmp_max': '17', 'tmp_min': '12', 'uv_index': '4', 'vis': '24', 'wind_deg': '257', 'wind_dir': 'SW', 'wind_sc': '4-5', 'wind_spd': '25'}, {'cond_code_d': '999', 'cond_code_n': '999', 'cond_txt_d': '-', 'cond_txt_n': '-', 'date': '2020-07-06', 'time': '2020-07-06 00:00:00', 'hum': '-', 'pcpn': '-', 'pop': '-', 'pres': '-', 'tmp_max': '-', 'tmp_min': '-', 'uv_index': '-', 'vis': '-', 'wind_deg': '-', 'wind_dir': '--', 'wind_sc': '--', 'wind_spd': '-'}], 'basic': {'cid': 'NL2759879', 'location': 'Almere-Stad', 'cnty': 'Netherlands', 'lat': '52.36700058', 'lon': '5.21799994', 'tz': '+1.00'}, 'update': {'loc': '2020-06-29 22:49:00', 'utc': '2020-06-29 21:49:00'}, 'status': 'ok'}]}, 'inverter': [{'sn': '93000', 'dict': {'left': [{'key': 'Model', 'value': 'GW3000D-NS', 'unit': '', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'S/N', 'value': '93000', 'unit': '', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'Checkcode', 'value': '024982', 'unit': '', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'Capaciteit', 'value': '3', 'unit': 'kW', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'Connected', 'value': '05.15.2019 20:59:09', 'unit': '', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'Vermogen', 'value': '0.238', 'unit': 'kW', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'Uitgangsspanning', 'value': '227.1', 'unit': 'V', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'AC Current', 'value': '1.3', 'unit': 'A', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'AC Frequency', 'value': '49.99', 'unit': 'Hz', 'isFaultMsg': 0, 'faultMsgCode': 0}], 'right': [{'key': 'Binnentemperatuur', 'value': '28.2', 'unit': '℃', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'DC Voltage/Current1', 'value': '172.7/0.9', 'unit': 'V/A', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'DC Voltage/Current2', 'value': '178.5/0.6', 'unit': 'V/A', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'DC Voltage/Current3', 'value': '--', 'unit': 'V/A', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'DC Voltage/Current4', 'value': '--', 'unit': 'V/A', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'String Current1', 'value': '--', 'unit': 'A', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'String Current2', 'value': '--', 'unit': 'A', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'String Current3', 'value': '--', 'unit': 'A', 'isFaultMsg': 0, 'faultMsgCode': 0}, {'key': 'String Current4', 'value': '--', 'unit': 'A', 'isFaultMsg': 0, 'faultMsgCode': 0}]}, 'is_stored': False, 'name': 'JP Energy #1', 'in_pac': 6555.9, 'out_pac': 238.0, 'eday': 0.3, 'emonth': 470.0, 'etotal': 4081.4, 'status': 1, 'turnon_time': '05/16/2019 02:59:09', 'releation_id': '5e099eb3-63cf-4de0-b843', 'type': 'GW3000D-NS', 'capacity': 3.0, 'd': {'pw_id': '6bc75339-f48c-440f-a096', 'capacity': '3kW', 'model': 'GW3000D-NS', 'output_power': '238W', 'output_current': '1.3A', 'grid_voltage': '227.1V', 'backup_output': '4294967.295V/0W', 'soc': '200%', 'soh': '0%', 'last_refresh_time': '06.30.2020 10:27:59', 'work_mode': 'Wait Mode', 'dc_input1': '172.7V/0.9A', 'dc_input2': '178.5V/0.6A', 'battery': '65535V/6553.5A/429483622W', 'bms_status': 'Discharging', 'warning': 'Over Temperature/Under Temperature/Cell Voltage Differences/Over Total Voltage/Discharge Over Current/Charge Over Current/Under SOC/Under Total Voltage/Communication Fail/Output Short/SOC Too High/BMS Module Fault/BMS System Fault/BMS Internal Fault/TBD/TBD', 'charge_current_limit': '1A', 'discharge_current_limit': '0A', 'firmware_version': 101008.0, 'creationDate': '06/30/2020 16:27:59', 'eDay': 0.3, 'eTotal': 4081.4, 'pac': 238.0, 'hTotal': 4945.0, 'vpv1': 172.7, 'vpv2': 178.5, 'vpv3': 6553.5, 'vpv4': 6553.5, 'ipv1': 0.9, 'ipv2': 0.6, 'ipv3': 6553.5, 'ipv4': 6553.5, 'vac1': 227.1, 'vac2': 6553.5, 'vac3': 6553.5, 'iac1': 1.3, 'iac2': 6553.5, 'iac3': 6553.5, 'fac1': 49.99, 'fac2': 655.35, 'fac3': 655.35, 'istr1': 0.0, 'istr2': 0.0, 'istr3': 0.0, 'istr4': 0.0, 'istr5': 0.0, 'istr6': 0.0, 'istr7': 0.0, 'istr8': 0.0, 'istr9': 0.0, 'istr10': 0.0, 'istr11': 0.0, 'istr12': 0.0, 'istr13': 0.0, 'istr14': 0.0, 'istr15': 0.0, 'istr16': 0.0}, 'it_change_flag': False, 'tempperature': 28.2, 'check_code': '024982', 'next': None, 'prev': None, 'next_device': {'sn': None, 'isStored': False}, 'prev_device': {'sn': None, 'isStored': False}, 'invert_full': {'sn': '93000', 'powerstation_id': '6bc75339-f48c-440f-a096', 'name': 'JP Energy #1', 'model_type': 'GW3000D-NS', 'change_type': 0, 'change_time': 0, 'capacity': 3.0, 'eday': 0.3, 'iday': 0.0672, 'etotal': 4081.4, 'itotal': 914.2336, 'hour_total': 4945.0, 'status': 1, 'turnon_time': 1557946749193, 'pac': 238.0, 'tempperature': 28.2, 'vpv1': 172.7, 'vpv2': 178.5, 'vpv3': 6553.5, 'vpv4': 6553.5, 'ipv1': 0.9, 'ipv2': 0.6, 
Jun 30 10:28:15 vps gw2pvo[18459]: INFO     Normal, 238.0 W now, 0.3 kWh today, 4081.4 kWh all time, 227.1 V grid, 172.7 V PV
Jun 30 10:28:15 vps gw2pvo[18459]: DEBUG    Starting new HTTPS connection (1): api.darksky.net:443
Jun 30 10:28:15 vps gw2pvo[18459]: DEBUG    https://api.darksky.net:443 "GET /forecast/00055055a01b1a5ccfe08565cd317f3b/52.374063,5.241989?units=si&exclude=minutely,hourly,daily,alerts,flags HTTP/1.1" 200 435
Jun 30 10:28:15 vps gw2pvo[18459]: DEBUG    {'d': '20200630', 't': '10:28', 'v1': 300, 'v2': 238, 'v5': 17.3, 'v6': 227.1}
Jun 30 10:28:15 vps gw2pvo[18459]: DEBUG    Starting new HTTPS connection (1): pvoutput.org:443
Jun 30 10:28:16 vps gw2pvo[18459]: DEBUG    https://pvoutput.org:443 "POST /service/r2/addstatus.jsp HTTP/1.1" 200 None

**Comment by markruys** [comment]
Now I understand we're talking about two different requests:
* support for multiple inverters
* support for multiple strings

So let's keep this issue to sum voltages for multiple strings. That's an easy change, I'll implement it.

**Comment by X-Wizard** [comment]
Correct, my request was support for multiple string.

**Comment by X-Wizard** [comment]
The modification for the sum (voltage) of both strings works perfectly!

Thanks!
