### ISSUE TITLE
Script needs adjusting - Changes to GoodWe website

### ISSUE THREAD

**Issue by Koploper** [markruys/gw2pvo#2]
Hi Mark,

I've been using your scripts for uploading my GoodWe PV generation data to PVOutput for the last few months. It worked conveniently. I especially found your tool to upload historical data very helpful.

A few days ago, due to the new privay legislation, Goodwe added a European server to deal with european data. It also seems that the URL to fetch the data does no longer work and that you need to log in before you can retrieve the data.

I have been looking for an alteranive and found one at https://github.com/zonoskar/Goodwe2PVoutput, which seems to work with the new server, but it lacks the tools to upload historical data. 

I f you have time, an update of gw2pvo would be greatly appriciated!

My best regards,

Koploper

**Comment by markruys** [comment]
Ah, let me check this.

**Comment by markruys** [comment]
Thanks for the link. I've update gw2pvo to use https (for both APIs), and added an option to set the region. In your case that would we `--gw-region EU`. Can you please test if it works for you too?

**Comment by Koploper** [comment]
Hi Mark,

Works for me too.

Thanks!

Koploper
