### ISSUE TITLE
Again energy did not restart the next day

### ISSUE THREAD

**Issue by Merlin1201** [markruys/gw2pvo#29]
Same problem again, the new day did not start with  zero.
And yes I had the latest update.

**Comment by kingfisher02** [comment]
Same problem here yesterday (10 August), but today it is fine again.

**Comment by markruys** [comment]
I have to close this issue as it's too vague. It contains no problem description, example, or means how to reproduce it. Feel free te reopen it if you have a detailed issue report.

**Comment by markruys** [comment]
I think the issue you're facing is described in #20. The fix is to use `--skip-offline`.
