### ISSUE TITLE
voltage and string power

### ISSUE THREAD

**Issue by wiljums** [markruys/gw2pvo#31]
can you add:

- voltage of string 1
- voltage of string 2
- Generated power of string 1 (DC Voltage * DC Current * efficiency)
- Generated power of string 1 (DC Voltage * DC Current * efficiency)

**Comment by X-Wizard** [comment]
See issue 19

**Comment by markruys** [comment]
In #19, I propose some code to average/sum multiple inverters/strings. Would that work for you?

**Comment by wiljums** [comment]
Ok for me to close this one and proceed in #19
