### ISSUE TITLE
Is this the swagger api documentation?

### ISSUE THREAD

**Issue by lakeman** [markruys/gw2pvo#39]
"GoodWe access is based on the undocumented API used by mobile apps."

Is it undocumented though?

After a cursory inspection, this looks promising;
http://globalapi.sems.com.cn:82/swagger/ui/index

**Comment by lakeman** [comment]
All the responses that come back are wrapped in;

```json
{
  "language": "en",
  "function": null,
  "hasError": false,
  "msg": "success",
  "code": "0",
  "data": { },
  "components": { }
}
```

Otherwise this is probably right.

**Comment by markruys** [comment]
Thanks for the reference, I've updated the README.md
