### ISSUE TITLE
SEMS Portal

### ISSUE THREAD

**Issue by Sephyr0s** [markruys/gw2pvo#4]
Hi, so today my Goodwe user stopped working. I guess to force us to the new SEMS Portal. I guess unless you're going to modify it to work with SEMS it's going to make this script obsolete.

**Comment by markruys** [comment]
Most likely we need PR https://github.com/markruys/gw2pvo/pull/3. I'll try to merge it soon now.

**Comment by markruys** [comment]
I've release [1.2.0](https://github.com/markruys/gw2pvo/releases/tag/1.2.0), which should address the issue. Please let us now how it works for you.

**Comment by peternijssen** [comment]
For me it kept working on 1.1.0 (for whatever reason). However, I just updated to 1.2.1 and everything seems to work fine as far as I can see right now. Just waiting for the sun to shine ;)

Thanks Mark for your work on this tool!

**Comment by Sephyr0s** [comment]
Cheers, installed it and it works like a charm. :)
