### ISSUE TITLE
gw2pvo.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by Ralf7** [markruys/gw2pvo#6]
Dear Mark,
I've tried to use your script but I receive an error and have no idea why, I hope you can help me. I have no coding/programming skills.
I'm using a Raspberry Pi 2+ with Raspbian Stretch installed. 
Python version is 3.5.3 and PIP version is 9.0.1
I followed all your instructions but at the line 'sudo systemctl status gw2pvo' I receive an error, see the attachment below:
![knipsel](https://user-images.githubusercontent.com/45140826/48671137-fe70fb00-eb23-11e8-9001-e98480648264.JPG)

**Comment by markruys** [comment]
Screenshot doesn't show a lot of info actually. Does /var/log/syslog show anything unusual? You could try to run the gw2pvo command directly and get some more understanding of what went wrong.

**Comment by Ralf7** [comment]
Every 10 minutes this is written in the syslog file:
![knipsel 2](https://user-images.githubusercontent.com/45140826/48679940-619b7580-eb96-11e8-91cc-3c5157652ef8.JPG)
I searched using Google what it means, but I couldn't find a solution.

I don't exactly know what you mean by running the gw2pvo command directly, because I'm a beginner in Linux/Python. But maybe this attachment is useful.
![knipsel 3](https://user-images.githubusercontent.com/45140826/48680041-5ac13280-eb97-11e8-9f07-f95963082fe6.JPG)

**Comment by eNeRGy164** [comment]
It seems something goes wrong when authenticating against the SEMS API. Is your account activated and can you login at https://www.semsportal.com/ with the same credentials you provide at the command line?
The application doesn't use the older goodwe-power.com portal.

**Comment by Ralf7** [comment]
I double checked and copy/paste it to make sure I didn't make a mistake. I can login using the new SEMS portal and am using exactly the same credentials in the gw2pvo.service script file. The gw-account is my emailaddress and the gw-password is obviously the password, which contains upper case, lower case, numbers and a under score symbol.

**Comment by markruys** [comment]
The logs show it can't find the program gw2pvo in `/usr/local/bin`. I suspect the installation went wrong. Can you please try again:
```
pip install https://github.com/markruys/gw2pvo/releases/download/1.2.1/gw2pvo-1.2.1.tar.gz
```
and show us the output? If it fails, you could try:
```
pip3 install https://github.com/markruys/gw2pvo/releases/download/1.2.1/gw2pvo-1.2.1.tar.gz
```
Also from this I would like to see the result.

**Comment by Ralf7** [comment]
Only the command starting with pip3 works for me. 
This is the result:
![opnieuw installeren](https://user-images.githubusercontent.com/45140826/48725743-63644800-ec2d-11e8-9baa-d94979b0f802.JPG)

I saved the screenshot of the initial installation on Saturday, see below:
![eerste installatie](https://user-images.githubusercontent.com/45140826/48725782-7f67e980-ec2d-11e8-8e61-6123dec658e5.jpg)

After reinstallation I checked the gw2pvo.service file using sudo nano gw2pvo.service.
Everything was still there, so I used CTRL+X to EXIT (or do I need to use a different command, I see for example READ?)
Then I entered the systemctl commands, Unfortunately I'm still receiving exactly the same error at sudo systemctl status gw2pvo.

Do I need to upgrade my pip version? I have 9.0.1

**Comment by Ralf7** [comment]
It looks like installing with sudo was the trick!
When I run sudo systemctl status gw2pvo I don't receive an error and in my PVOutput account I see the live page with new data every 5 minutes. 
After following your commands in the previous post I entered sudo journalctl -u gw2pvo -f

**Comment by Ralf7** [comment]
The script runs now for almost 2 weeks and I didn't find any new problems, so I close this issue.

**Comment by markruys** [comment]
Okay, I've updated the documentation and added sudo.
