### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by varkanoid** [markruys/gw2pvo#68]
Hi,

sorry see the attached picture. I`m a right noob what am I doing wrong ?

regards

Jools

![Screenshot 2022-12-08 153056](https://user-images.githubusercontent.com/16356424/206487259-4e5d19a2-b1ca-4310-ad95-457c665d43ba.jpg)

**Comment by eNeRGy164** [comment]
You don't have pip installed

**Comment by varkanoid** [comment]
I enabled it at install ? 
![Screenshot 2022-12-08 163059](https://user-images.githubusercontent.com/16356424/206507890-f1fc7551-1b95-4fb4-8059-edc1186df363.jpg)

**Comment by varkanoid** [comment]
I`ll figure it out I wont take up anymore of your time.
