### ISSUE TITLE
All imported logs with --date are 1 day ahead

### ISSUE THREAD

**Issue by robinbohnen** [markruys/gw2pvo#8]
When I import with this command: gw2pvo --gw-station-id <station> --gw-account <account> --gw-password <pw> --pvo-system-id <id> --pvo-api-key <key> --log debug --date 2018-12-13 --darksky-api-key <key>

It will import the data of 2018-12-12 (at GoodWe) to 2018-12-13 (at Pvoutput).
How can I fix this?

**Comment by eNeRGy164** [comment]
I think this is because the timezone code has been changed/removed in the latest commit?

**Comment by markruys** [comment]
Might be very well the case. The original code gave errors (cf issue #7), so we have to look into this again.

**Comment by vijghph** [comment]
I confirm the issue: the retroactive loading of data is setup day "one+1". To be fixed.

**Comment by vijghph** [comment]
I noticed the JSON response for GetPowerStationPowerAndIncomeByDay() contains a sequence of data for day-1 then the day itself. So the fix maybe actually quite simple. I'll propose it.

**Comment by Koploper** [comment]
I confirm the issue also. Can the fix be added to the code?

**Comment by vijghph** [comment]
Any hope of getting a build with the proposed fix?

**Comment by daemenseth** [comment]
I can confirm the fix is working. I hope there is fast a build with the fixes

**Comment by lbbrhzn** [comment]
the fix from vijghph is working for me as well.

**Comment by lbbrhzn** [comment]
Unfortunately, this fix is does seem to work for the current day.

The issue appear to be that GetPowerStationPowerAndIncomeByDay does not return the running total for the current day. 

However,  GetPowerStationPacByDayForApp appears to have this info in the 'today_power' field.  Note that it always contains the value for the *current* day, not for the requested day!!
